spring.datasource.url=jdbc:postgresql://localhost:5432/MyBot
telegram.bot.token=

spring.datasource.username=postgres
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=validate
spring.liquibase.change-log=classpath:liquibase/changelog-master.yml

server.port=8081
